export const TRADE_CHECKLISTS: Record<string, string[]> = {
  Maler: [
    'Untergrund geprüft und vorbereitet',
    'Abdeckung von Möbeln und Böden',
    'Grundierung aufgetragen',
    'Anstrich / Farbe gleichmäßig aufgetragen',
    'Zweiter Anstrich nach Trockenzeit',
    'Abklebeband entfernt',
    'Reinigung des Arbeitsbereichs',
    'Farbton vom Kunden abgenommen',
  ],
  Elektriker: [
    'Stromkreis abgesichert und geprüft',
    'Leitungsführung dokumentiert',
    'Verbindungen fachgerecht ausgeführt',
    'Isolierung geprüft',
    'FI-Schutzschalter getestet',
    'Funktionsprüfung aller Geräte',
    'VDE-Prüfung durchgeführt',
    'Messprotokoll erstellt',
  ],
  Sanitär: [
    'Wasserleitung abgesperrt',
    'Dichtheit aller Verbindungen geprüft',
    'Druckprüfung durchgeführt',
    'Abfluss auf Durchfluss getestet',
    'Silikon / Dichtungen erneuert',
    'Thermostatventile eingestellt',
    'Warmwassertemperatur geprüft (min. 60°C)',
    'Übergabe und Einweisung Kunde',
  ],
  Schreiner: [
    'Maße vor Ort aufgenommen',
    'Material und Oberfläche geprüft',
    'Passgenauigkeit kontrolliert',
    'Beschläge und Scharniere eingestellt',
    'Schleif- und Lackierarbeiten abgeschlossen',
    'Funktion aller beweglichen Teile geprüft',
    'Oberfläche auf Beschädigungen kontrolliert',
    'Arbeitsbereich gereinigt',
  ],
  Fliesenleger: [
    'Untergrund geprüft (eben, tragfähig)',
    'Abdichtung aufgetragen und getrocknet',
    'Fliesenverlegung nach Plan',
    'Fugenabstände gleichmäßig',
    'Fugenmörtel eingebracht',
    'Silikonfugen in Ecken und Anschlüssen',
    'Oberfläche gereinigt und versiegelt',
    'Abnahme mit Kunde',
  ],
  Dachdecker: [
    'Dachfläche inspiziert',
    'Alte Eindeckung entfernt',
    'Unterdachbahn verlegt',
    'Lattung kontrolliert / erneuert',
    'Neue Eindeckung verlegt',
    'Firstabdeckung montiert',
    'Dichtigkeit geprüft',
    'Fallrohre und Regenrinnen kontrolliert',
  ],
  Gerüstbauer: [
    'Standfestigkeit des Untergrunds geprüft',
    'Aufbauplan befolgt',
    'Alle Verbindungen gesichert',
    'Geländer und Absturzsicherung montiert',
    'Belagsbretter vollständig verlegt',
    'Zugang und Aufstiege gesichert',
    'Lastangaben eingehalten',
    'Abnahmeprotokoll erstellt',
  ],
  Bodenleger: [
    'Untergrundfeuchte gemessen',
    'Untergrund geschliffen und gereinigt',
    'Dampfsperre / Trittschalldämmung verlegt',
    'Belag verlegt (Richtung und Muster)',
    'Übergänge und Schwellen montiert',
    'Sockelleisten angebracht',
    'Oberfläche gereinigt',
    'Abnahme mit Kunde',
  ],
  Metallbauer: [
    'Maße und Konstruktionsplan geprüft',
    'Material auf Fehler kontrolliert',
    'Schweißnähte / Verbindungen geprüft',
    'Oberflächenbehandlung (Schleifen, Entgraten)',
    'Beschichtung / Lackierung aufgetragen',
    'Montage und Befestigung geprüft',
    'Funktion beweglicher Teile kontrolliert',
    'Abnahme mit Kunde',
  ],
  Garten: [
    'Geländeplan und Bepflanzungsplan abgestimmt',
    'Boden vorbereitet (Aushub, Drainage)',
    'Pflanzen fachgerecht gesetzt',
    'Bewässerungsanlage geprüft',
    'Wege und Befestigungen verlegt',
    'Rasensaat / Rollrasen verlegt',
    'Abschlussreinigung',
    'Pflegehinweise an Kunde übergeben',
  ],
  Folierung: [
    'Untergrund gereinigt und entfettet',
    'Temperatur geprüft (15–25°C)',
    'Folie auf Maß zugeschnitten',
    'Blasen und Falten vermieden',
    'Kanten und Ecken sauber angedrückt',
    'Überstände abgeschnitten',
    'Endreinigung',
    'Abnahme mit Kunde (Foto)',
  ],
  Reinigung: [
    'Leistungsverzeichnis geprüft',
    'Reinigungsmittel geeignet für Untergrund',
    'Alle Flächen gereinigt',
    'Sanitäranlagen desinfiziert',
    'Böden gewischt / gesaugt',
    'Fenster innen gereinigt',
    'Müll entsorgt',
    'Abnahme mit Kunde',
  ],
}

export const DEFAULT_CHECKLIST = [
  'Auftrag vollständig ausgeführt',
  'Arbeitsbereich gereinigt',
  'Material und Werkzeug vollständig',
  'Mängel dokumentiert',
  'Abnahme mit Kunde',
]

export function getChecklistForTrade(trade?: string | null): string[] {
  if (!trade) return DEFAULT_CHECKLIST
  return TRADE_CHECKLISTS[trade] ?? DEFAULT_CHECKLIST
}
